//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicFitnessFertilizer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DFFDBEntities : DbContext
    {
        public DFFDBEntities()
            : base("name=DFFDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LawnTool> LawnTools { get; set; }
        public virtual DbSet<Loaner> Loaners { get; set; }
        public virtual DbSet<Member> Members { get; set; }
    }
}
